# Generated by Django 5.0.4 on 2024-04-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200, unique=True)),
                ('total_price', models.SmallIntegerField()),
                ('food', models.ManyToManyField(to='food.food')),
            ],
        ),
    ]
